### PR TITLE
Update location information for Winnipeg Math Jam

### PR DESCRIPTION
**Pull request by stevenschroeder**
Effective October, 2018, location was changed to Tony Roma's at 1500 Pembina Hwy as the previous location (Indulge Bistro & Wine Bar) is closed.

### CODE REVIEW

**Comment by stevenschroeder** [comment]
Great, thanks.  Just gave it a quick smoke test and the information appears to have updated correctly.

**Comment by katiesteckles** [comment]
Thanks - good work! (It's nice when people get how to update things and
don't need any help from me :P)
Have a good Jam!
Katie

**Comment by stevenschroeder** [comment]
Appreciate the positive reinforcement.  It took me a while to get myself up to speed - this was my first pull request!

**Comment by katiesteckles** [comment]
Even better! :)

**Pull request merged**
